In [3]:
import numpy as np
import pandas as pd

In [4]:
movies=pd.read_csv('tmdb_5000_movies.csv')

In [5]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [6]:
credits=pd.read_csv('tmdb_5000_credits.csv')

In [7]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [8]:
movies=movies.merge(credits,on='title')

In [9]:
movies.shape

(4809, 23)

In [10]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [11]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [12]:
#IMPORTANT COLUMNS TO KEEP
#Genre
#id
#keywords
#Title
#Overview
#Cast 
#Crew

movies=movies[['genres','title','id','keywords','overview','cast','crew']]

In [13]:
movies.shape

(4809, 7)

In [14]:
movies.isnull().sum()

genres      0
title       0
id          0
keywords    0
overview    3
cast        0
crew        0
dtype: int64

In [15]:
movies.dropna(inplace=True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\3786870272.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.dropna(inplace=True)

In [16]:
movies.isnull().sum()

genres      0
title       0
id          0
keywords    0
overview    0
cast        0
crew        0
dtype: int64

In [17]:
movies.duplicated().sum()

np.int64(0)

In [18]:
movies

,genres,title,id,keywords,overview,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",El Mariachi just wants to play his guitar and ...,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",Newlyweds,72766,[],A newlywed couple's honeymoon is upended by th...,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","Signed, Sealed, Delivered",231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,[],Shanghai Calling,126186,[],When ambitious New York attorney Sam is sent t...,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,"[{""id"": 99, ""name"": ""Documentary""}]",My Date with Drew,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",Ever since the second grade when he first saw ...,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [19]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [20]:
#[Action,Adventure,Fantasy,Scifi]

In [21]:
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [22]:
import ast#for converting dictionary to list

In [23]:
movies['genres']=movies['genres'].apply(convert)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\1567952790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(convert)

In [24]:
movies.head()

,genres,title,id,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",Spectre,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies['keywords']=movies['keywords'].apply(convert)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\1621871954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(convert)

In [26]:
movies.head()

,genres,title,id,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
def convert1(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break    
    return L

In [28]:
movies['cast']=movies['cast'].apply(convert1)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\3009813742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(convert1)

In [29]:
movies.head()

,genres,title,id,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [30]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=="Director":
            L.append(i['name'])
            break
    return L

In [31]:
movies['crew']=movies['crew'].apply(fetch_director)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\766358383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(fetch_director)

In [32]:
movies.head()

,genres,title,id,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bondâ€™s past sends him o...,"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\1104793012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['overview']=movies['overview'].apply(lambda x:x.split())

In [34]:
movies.head()

,genres,title,id,keywords,overview,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"[culture clash, future, space war, space colon...","[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[ocean, drug abuse, exotic island, east india ...","[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,"[Action, Adventure, Crime]",Spectre,206647,"[spy, based on novel, secret agent, sequel, mi...","[A, cryptic, message, from, Bondâ€™s, past, send...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[dc comics, crime fighter, terrorist, secret i...","[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"[based on novel, mars, medallion, space travel...","[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [35]:
#Removing spaces to avoid confusion during tags
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\2313674165.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\2313674165.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\2313674165.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])
C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\2313674165.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

In [36]:
movies['tags']=movies['overview']+movies['keywords']+movies['cast']+movies['crew']

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\1108887321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['overview']+movies['keywords']+movies['cast']+movies['crew']

In [37]:
new_movie=movies[['title','id','tags']]

In [38]:
new_movie

,title,id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,El Mariachi,9367,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,Newlyweds,72766,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,"Signed, Sealed, Delivered",231617,"[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,Shanghai Calling,126186,"[When, ambitious, New, York, attorney, Sam, is..."
4808,My Date with Drew,25975,"[Ever, since, the, second, grade, when, he, fi..."

In [39]:
new_movie['tags'].head()

0    [In, the, 22nd, century,, a, paraplegic, Marin...
1    [Captain, Barbossa,, long, believed, to, be, d...
2    [A, cryptic, message, from, Bondâ€™s, past, send...
3    [Following, the, death, of, District, Attorney...
4    [John, Carter, is, a, war-weary,, former, mili...
Name: tags, dtype: object

In [40]:
#converting 'tags'list to string



new_movie['tags']=new_movie['tags'].apply(lambda x:" ".join(x))

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\509607991.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tags']=new_movie['tags'].apply(lambda x:" ".join(x))

In [41]:
new_movie.head()

,title,id,tags
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,206647,A cryptic message from Bondâ€™s past sends him o...
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...
4,John Carter,49529,"John Carter is a war-weary, former military ca..."

In [42]:
new_movie['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [43]:
new_movie['tags']=new_movie['tags'].apply(lambda x:x.lower())

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\879706796.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tags']=new_movie['tags'].apply(lambda x:x.lower())

TEXT VECTORIZATION

In [44]:
#converting tags to vectors

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [45]:
vectors=cv.fit_transform(new_movie['tags']).toarray()

In [46]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [47]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [48]:
#applying stemming
#['loved,loving,love]->[love,love,love]

In [49]:
import nltk

In [50]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [51]:



def stem(text):
    y=[]

    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [52]:
new_movie['tags'][0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [53]:
ps.stem('in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron')

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron'

In [54]:
new_movie['tags']=new_movie['tags'].apply(stem)  #STEMMING APPLIED

C:\Users\KIIT\AppData\Local\Temp\ipykernel_17264\270963611.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_movie['tags']=new_movie['tags'].apply(stem)  #STEMMING APPLIED

In [55]:
#Calculating distance between vectors using cosine distance

In [56]:
from sklearn.metrics.pairwise import cosine_similarity
similarity=cosine_similarity(vectors)

In [57]:
similarity[0]

array([1.        , 0.        , 0.        , ..., 0.        , 0.02993422,
       0.        ])

In [58]:
similarity[1]

array([0.        , 1.        , 0.        , ..., 0.02951407, 0.        ,
       0.        ])

A function to  recommend five  similar movies

In [59]:
list(enumerate(similarity[0]))#holds the index position of the cosine distancces of  each movie

[(0, np.float64(1.0000000000000002)),
 (1, np.float64(0.0)),
 (2, np.float64(0.0)),
 (3, np.float64(0.021780342093451605)),
 (4, np.float64(0.11359236684941297)),
 (5, np.float64(0.05184758473652127)),
 (6, np.float64(0.0)),
 (7, np.float64(0.0582716546748065)),
 (8, np.float64(0.0)),
 (9, np.float64(0.0)),
 (10, np.float64(0.0)),
 (11, np.float64(0.030358837035945812)),
 (12, np.float64(0.0)),
 (13, np.float64(0.0)),
 (14, np.float64(0.0)),
 (15, np.float64(0.0)),
 (16, np.float64(0.0)),
 (17, np.float64(0.07136791021047098)),
 (18, np.float64(0.07401205672371727)),
 (19, np.float64(0.02358333153182891)),
 (20, np.float64(0.0)),
 (21, np.float64(0.03394221166510653)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.0)),
 (25, np.float64(0.01983408759395048)),
 (26, np.float64(0.09379580992210838)),
 (27, np.float64(0.12828950144769635)),
 (28, np.float64(0.03592106040535498)),
 (29, np.float64(0.026198125853112306)),
 (30, np.float64(0.0)),
 (31, np.float64(0.07332355751067667)),
 (32, np.float64(0.0254000254000381)),
 (33, np.float64(0.0)),
 (34, np.float64(0.0)),
 (35, np.float64(0.0)),
 (36, np.float64(0.12320822072673948)),
 (37, np.float64(0.03126526997403613)),
 (38, np.float64(0.0)),
 (39, np.float64(0.0)),
 (40, np.float64(0.0)),
 (41, np.float64(0.08122955416108235)),
 (42, np.float64(0.0)),
 (43, np.float64(0.0535479552601666)),
 (44, np.float64(0.0)),
 (45, np.float64(0.0508000508000762)),
 (46, np.float64(0.06670373459650701)),
 (47, np.float64(0.16508332072280235)),
 (48, np.float64(0.024670685574572422)),
 (49, np.float64(0.03456505649101418)),
 (50, np.float64(0.0)),
 (51, np.float64(0.02358333153182891)),
 (52, np.float64(0.06558258357839529)),
 (53, np.float64(0.0)),
 (54, np.float64(0.0)),
 (55, np.float64(0.021780342093451605)),
 (56, np.float64(0.041204282171516456)),
 (57, np.float64(0.031750031750047626)),
 (58, np.float64(0.0)),
 (59, np.float64(0.02162193750322053)),
 (60, np.float64(0.031750031750047626)),
 (61, np.float64(0.08712136837380642)),
 (62, np.float64(0.0)),
 (63, np.float64(0.05029954548278569)),
 (64, np.float64(0.0)),
 (65, np.float64(0.0)),
 (66, np.float64(0.0)),
 (67, np.float64(0.1018266349953196)),
 (68, np.float64(0.03829197905337418)),
 (69, np.float64(0.018932061141568826)),
 (70, np.float64(0.0)),
 (71, np.float64(0.0)),
 (72, np.float64(0.0)),
 (73, np.float64(0.0)),
 (74, np.float64(0.19172686248267187)),
 (75, np.float64(0.03394221166510653)),
 (76, np.float64(0.0)),
 (77, np.float64(0.016260700012185932)),
 (78, np.float64(0.0)),
 (79, np.float64(0.0)),
 (80, np.float64(0.0)),
 (81, np.float64(0.042933879074109185)),
 (82, np.float64(0.03126526997403613)),
 (83, np.float64(0.11503946170861017)),
 (84, np.float64(0.04716666306365782)),
 (85, np.float64(0.057114371815885016)),
 (86, np.float64(0.03456505649101418)),
 (87, np.float64(0.06670373459650701)),
 (88, np.float64(0.03522349768381735)),
 (89, np.float64(0.050027800947380255)),
 (90, np.float64(0.0)),
 (91, np.float64(0.0704469953676347)),
 (92, np.float64(0.026198125853112306)),
 (93, np.float64(0.0)),
 (94, np.float64(0.07490058862731383)),
 (95, np.float64(0.083141099321054)),
 (96, np.float64(0.0)),
 (97, np.float64(0.0)),
 (98, np.float64(0.0)),
 (99, np.float64(0.0)),
 (100, np.float64(0.0)),
 (101, np.float64(0.0)),
 (102, np.float64(0.049341371149144844)),
 (103, np.float64(0.024670685574572422)),
 (104, np.float64(0.0)),
 (105, np.float64(0.03919309008348103)),
 (106, np.float64(0.0)),
 (107, np.float64(0.025149772741392844)),
 (108, np.float64(0.10709591052033318)),
 (109, np.float64(0.0)),
 (110, np.float64(0.0)),
 (111, np.float64(0.06788442333021306)),
 (112, np.float64(0.0)),
 (113, np.float64(0.0)),
 (114, np.float64(0.0)),
 (115, np.float64(0.0)),
 (116, np.float64(0.0)),
 (117, np.float64(0.0)),
 (118, np.float64(0.0)),
 (119, np.float64(0.027389551783238836)),
 (120, np.float64(0.0)),
 (121, np.float64(0.0)),
 (122, np.float64(0.0)),
 (123, np.float64(0.05477910356647767)),
 (124, np.float64(0.026481357066618805)),
 (125, np.float64(0.034726199819070075)),
 (126, np.float64(0.03225806451612904)),
 (127, np.float64(0.04388455990411494)),
 (128, np.float64(0.0)),
 (129, np.float64(0.02913582733740325)),
 (130, np.float64(0.0)),
 (131, np.float64(0.031750031750047626)),
 (132, np.float64(0.024217973984824143)),
 (133, np.float64(0.0)),
 (134, np.float64(0.07658395810674835)),
 (135, np.float64(0.0)),
 (136, np.float64(0.0)),
 (137, np.float64(0.036854230359837384)),
 (138, np.float64(0.0)),
 (139, np.float64(0.048435947969648285)),
 (140, np.float64(0.028049635672660722)),
 (141, np.float64(0.08712136837380642)),
 (142, np.float64(0.03829197905337418)),
 (143, np.float64(0.0)),
 (144, np.float64(0.0)),
 (145, np.float64(0.0)),
 (146, np.float64(0.018624202231923414)),
 (147, np.float64(0.0)),
 (148, np.float64(0.04016096644512494)),
 (149, np.float64(0.11791665765914455)),
 (150, np.float64(0.13912166872805048)),
 (151, np.float64(0.14400460822119582)),
 (152, np.float64(0.0)),
 (153, np.float64(0.04676523735449557)),
 (154, np.float64(0.0)),
 (155, np.float64(0.0)),
 (156, np.float64(0.04888237167378443)),
 (157, np.float64(0.04016096644512494)),
 (158, np.float64(0.05751973085430508)),
 (159, np.float64(0.0)),
 (160, np.float64(0.042630455631948755)),
 (161, np.float64(0.0)),
 (162, np.float64(0.0)),
 (163, np.float64(0.0)),
 (164, np.float64(0.0)),
 (165, np.float64(0.0)),
 (166, np.float64(0.03394221166510653)),
 (167, np.float64(0.0)),
 (168, np.float64(0.060717674071891624)),
 (169, np.float64(0.05239625170622461)),
 (170, np.float64(0.05029954548278569)),
 (171, np.float64(0.0)),
 (172, np.float64(0.048001536073731935)),
 (173, np.float64(0.027389551783238836)),
 (174, np.float64(0.03080205518168487)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0)),
 (177, np.float64(0.0)),
 (178, np.float64(0.0)),
 (179, np.float64(0.046373889576016826)),
 (180, np.float64(0.0)),
 (181, np.float64(0.0)),
 (182, np.float64(0.029934217004462485)),
 (183, np.float64(0.020207175225248872)),
 (184, np.float64(0.14567913668701626)),
 (185, np.float64(0.0)),
 (186, np.float64(0.0)),
 (187, np.float64(0.0)),
 (188, np.float64(0.0)),
 (189, np.float64(0.046373889576016826)),
 (190, np.float64(0.02358333153182891)),
 (191, np.float64(0.0)),
 (192, np.float64(0.0)),
 (193, np.float64(0.023789303403490326)),
 (194, np.float64(0.0)),
 (195, np.float64(0.0)),
 (196, np.float64(0.0)),
 (197, np.float64(0.0)),
 (198, np.float64(0.0)),
 (199, np.float64(0.051315800579078544)),
 (200, np.float64(0.0)),
 (201, np.float64(0.0)),
 (202, np.float64(0.0)),
 (203, np.float64(0.0)),
 (204, np.float64(0.0)),
 (205, np.float64(0.0)),
 (206, np.float64(0.0420424211834425)),
 (207, np.float64(0.0)),
 (208, np.float64(0.049813548138671795)),
 (209, np.float64(0.0)),
 (210, np.float64(0.0)),
 (211, np.float64(0.0)),
 (212, np.float64(0.0)),
 (213, np.float64(0.023789303403490326)),
 (214, np.float64(0.0)),
 (215, np.float64(0.0)),
 (216, np.float64(0.0)),
 (217, np.float64(0.0)),
 (218, np.float64(0.0)),
 (219, np.float64(0.0)),
 (220, np.float64(0.1382602259640567)),
 (221, np.float64(0.0)),
 (222, np.float64(0.049813548138671795)),
 (223, np.float64(0.030358837035945812)),
 (224, np.float64(0.022809896167307987)),
 (225, np.float64(0.0)),
 (226, np.float64(0.0)),
 (227, np.float64(0.03394221166510653)),
 (228, np.float64(0.056099271345321444)),
 (229, np.float64(0.020878692266483083)),
 (230, np.float64(0.02262814111007102)),
 (231, np.float64(0.0)),
 (232, np.float64(0.0)),
 (233, np.float64(0.0)),
 (234, np.float64(0.0)),
 (235, np.float64(0.0)),
 (236, np.float64(0.07838618016696206)),
 (237, np.float64(0.0)),
 (238, np.float64(0.04525628222014204)),
 (239, np.float64(0.09274777915203365)),
 (240, np.float64(0.0)),
 (241, np.float64(0.0)),
 (242, np.float64(0.0)),
 (243, np.float64(0.028049635672660722)),
 (244, np.float64(0.03522349768381735)),
 (245, np.float64(0.03394221166510653)),
 (246, np.float64(0.049341371149144844)),
 (247, np.float64(0.0)),
 (248, np.float64(0.0)),
 (249, np.float64(0.08240856434303291)),
 (250, np.float64(0.0)),
 (251, np.float64(0.046373889576016826)),
 (252, np.float64(0.0)),
 (253, np.float64(0.024906774069335898)),
 (254, np.float64(0.03225806451612904)),
 (255, np.float64(0.0)),
 (256, np.float64(0.0)),
 (257, np.float64(0.03225806451612904)),
 (258, np.float64(0.0)),
 (259, np.float64(0.0)),
 (260, np.float64(0.14664711502135333)),
 (261, np.float64(0.0)),
 (262, np.float64(0.0)),
 (263, np.float64(0.0)),
 (264, np.float64(0.0)),
 (265, np.float64(0.0)),
 (266, np.float64(0.060717674071891624)),
 (267, np.float64(0.0)),
 (268, np.float64(0.0)),
 (269, np.float64(0.0)),
 (270, np.float64(0.056099271345321444)),
 (271, np.float64(0.0)),
 (272, np.float64(0.0)),
 (273, np.float64(0.0)),
 (274, np.float64(0.05208929972860511)),
 (275, np.float64(0.0704469953676347)),
 (276, np.float64(0.0)),
 (277, np.float64(0.024217973984824143)),
 (278, np.float64(0.02875986542715254)),
 (279, np.float64(0.056796183424706485)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0803219328902499)),
 (282, np.float64(0.0)),
 (283, np.float64(0.0)),
 (284, np.float64(0.0)),
 (285, np.float64(0.0)),
 (286, np.float64(0.0)),
 (287, np.float64(0.029934217004462485)),
 (288, np.float64(0.0)),
 (289, np.float64(0.0)),
 (290, np.float64(0.0)),
 (291, np.float64(0.0)),
 (292, np.float64(0.0)),
 (293, np.float64(0.0)),
 (294, np.float64(0.03522349768381735)),
 (295, np.float64(0.06451612903225808)),
 (296, np.float64(0.0)),
 (297, np.float64(0.026198125853112306)),
 (298, np.float64(0.0)),
 (299, np.float64(0.0)),
 (300, np.float64(0.11810771907149853)),
 (301, np.float64(0.1535959596644023)),
 (302, np.float64(0.0)),
 (303, np.float64(0.0)),
 (304, np.float64(0.03873467559917655)),
 (305, np.float64(0.14530784390894486)),
 (306, np.float64(0.03522349768381735)),
 (307, np.float64(0.07531100588381143)),
 (308, np.float64(0.04016096644512494)),
 (309, np.float64(0.0)),
 (310, np.float64(0.0)),
 (311, np.float64(0.11503946170861017)),
 (312, np.float64(0.06451612903225808)),
 (313, np.float64(0.08712136837380642)),
 (314, np.float64(0.0)),
 (315, np.float64(0.0)),
 (316, np.float64(0.0)),
 (317, np.float64(0.0)),
 (318, np.float64(0.0)),
 (319, np.float64(0.0)),
 (320, np.float64(0.0)),
 (321, np.float64(0.0)),
 (322, np.float64(0.12903225806451615)),
 (323, np.float64(0.0)),
 (324, np.float64(0.0)),
 (325, np.float64(0.046373889576016826)),
 (326, np.float64(0.0)),
 (327, np.float64(0.0)),
 (328, np.float64(0.0)),
 (329, np.float64(0.0)),
 (330, np.float64(0.03126526997403613)),
 (331, np.float64(0.0)),
 (332, np.float64(0.06558258357839529)),
 (333, np.float64(0.0)),
 (334, np.float64(0.029934217004462485)),
 (335, np.float64(0.0)),
 (336, np.float64(0.0)),
 (337, np.float64(0.0)),
 (338, np.float64(0.0)),
 (339, np.float64(0.0)),
 (340, np.float64(0.0)),
 (341, np.float64(0.0)),
 (342, np.float64(0.08526091126389751)),
 (343, np.float64(0.024906774069335898)),
 (344, np.float64(0.0)),
 (345, np.float64(0.0)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0)),
 (348, np.float64(0.03829197905337418)),
 (349, np.float64(0.0)),
 (350, np.float64(0.0)),
 (351, np.float64(0.0)),
 (352, np.float64(0.0)),
 (353, np.float64(0.0)),
 (354, np.float64(0.0)),
 (355, np.float64(0.0)),
 (356, np.float64(0.03522349768381735)),
 (357, np.float64(0.0)),
 (358, np.float64(0.0)),
 (359, np.float64(0.0)),
 (360, np.float64(0.0)),
 (361, np.float64(0.03126526997403613)),
 (362, np.float64(0.03666177875533833)),
 (363, np.float64(0.0508000508000762)),
 (364, np.float64(0.0)),
 (365, np.float64(0.059053859535749265)),
 (366, np.float64(0.0)),
 (367, np.float64(0.0)),
 (368, np.float64(0.07658395810674835)),
 (369, np.float64(0.0)),
 (370, np.float64(0.0)),
 (371, np.float64(0.0)),
 (372, np.float64(0.029526929767874632)),
 (373, np.float64(0.1567723603339241)),
 (374, np.float64(0.0)),
 (375, np.float64(0.023186944788008413)),
 (376, np.float64(0.0)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.0)),
 (380, np.float64(0.0)),
 (381, np.float64(0.0)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0)),
 (384, np.float64(0.0)),
 (385, np.float64(0.0)),
 (386, np.float64(0.0)),
 (387, np.float64(0.0)),
 (388, np.float64(0.0)),
 (389, np.float64(0.03829197905337418)),
 (390, np.float64(0.0)),
 (391, np.float64(0.02262814111007102)),
 (392, np.float64(0.0)),
 (393, np.float64(0.0)),
 (394, np.float64(0.0)),
 (395, np.float64(0.032791291789197645)),
 (396, np.float64(0.0)),
 (397, np.float64(0.03126526997403613)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0)),
 (400, np.float64(0.0)),
 (401, np.float64(0.03829197905337418)),
 (402, np.float64(0.0)),
 (403, np.float64(0.0)),
 (404, np.float64(0.03829197905337418)),
 (405, np.float64(0.0)),
 (406, np.float64(0.024000768036865967)),
 (407, np.float64(0.0)),
 (408, np.float64(0.0)),
 (409, np.float64(0.0)),
 (410, np.float64(0.02913582733740325)),
 (411, np.float64(0.0)),
 (412, np.float64(0.028398091712353243)),
 (413, np.float64(0.03225806451612904)),
 (414, np.float64(0.0)),
 (415, np.float64(0.03829197905337418)),
 (416, np.float64(0.0)),
 (417, np.float64(0.0)),
 (418, np.float64(0.041204282171516456)),
 (419, np.float64(0.0)),
 (420, np.float64(0.02913582733740325)),
 (421, np.float64(0.0)),
 (422, np.float64(0.08032193289024989)),
 (423, np.float64(0.028398091712353243)),
 (424, np.float64(0.0)),
 (425, np.float64(0.025923792368260635)),
 (426, np.float64(0.0)),
 (427, np.float64(0.0)),
 (428, np.float64(0.021466939537054593)),
 (429, np.float64(0.0)),
 (430, np.float64(0.059053859535749265)),
 (431, np.float64(0.0)),
 (432, np.float64(0.08216865534971651)),
 (433, np.float64(0.0)),
 (434, np.float64(0.0)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.0)),
 (438, np.float64(0.0)),
 (439, np.float64(0.03456505649101418)),
 (440, np.float64(0.0)),
 (441, np.float64(0.0)),
 (442, np.float64(0.0)),
 (443, np.float64(0.0)),
 (444, np.float64(0.0)),
 (445, np.float64(0.0)),
 (446, np.float64(0.0)),
 (447, np.float64(0.0)),
 (448, np.float64(0.027713699773684666)),
 (449, np.float64(0.0)),
 (450, np.float64(0.0)),
 (451, np.float64(0.0)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0)),
 (454, np.float64(0.10955820713295535)),
 (455, np.float64(0.0)),
 (456, np.float64(0.0535479552601666)),
 (457, np.float64(0.0)),
 (458, np.float64(0.026198125853112306)),
 (459, np.float64(0.0)),
 (460, np.float64(0.0)),
 (461, np.float64(0.13470397652008118)),
 (462, np.float64(0.0)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.12048289933537483)),
 (467, np.float64(0.025149772741392844)),
 (468, np.float64(0.0)),
 (469, np.float64(0.0254000254000381)),
 (470, np.float64(0.0)),
 (471, np.float64(0.0)),
 (472, np.float64(0.0)),
 (473, np.float64(0.0582716546748065)),
 (474, np.float64(0.0)),
 (475, np.float64(0.024906774069335898)),
 (476, np.float64(0.041204282171516456)),
 (477, np.float64(0.0)),
 (478, np.float64(0.0)),
 (479, np.float64(0.08240856434303291)),
 (480, np.float64(0.0)),
 (481, np.float64(0.0)),
 (482, np.float64(0.0)),
 (483, np.float64(0.03666177875533833)),
 (484, np.float64(0.0)),
 (485, np.float64(0.0)),
 (486, np.float64(0.0)),
 (487, np.float64(0.08032193289024989)),
 (488, np.float64(0.042933879074109185)),
 (489, np.float64(0.0)),
 (490, np.float64(0.04490132550669373)),
 (491, np.float64(0.0254000254000381)),
 (492, np.float64(0.03592106040535498)),
 (493, np.float64(0.0)),
 (494, np.float64(0.0)),
 (495, np.float64(0.12361284651454937)),
 (496, np.float64(0.0)),
 (497, np.float64(0.0)),
 (498, np.float64(0.0)),
 (499, np.float64(0.0)),
 (500, np.float64(0.0)),
 (501, np.float64(0.024441185836892216)),
 (502, np.float64(0.13856849886842332)),
 (503, np.float64(0.0)),
 (504, np.float64(0.0)),
 (505, np.float64(0.04356068418690321)),
 (506, np.float64(0.04233337566673017)),
 (507, np.float64(0.19925419255468715)),
 (508, np.float64(0.0)),
 (509, np.float64(0.0)),
 (510, np.float64(0.059053859535749265)),
 (511, np.float64(0.0)),
 (512, np.float64(0.03394221166510653)),
 (513, np.float64(0.06253053994807226)),
 (514, np.float64(0.0)),
 (515, np.float64(0.0)),
 (516, np.float64(0.0)),
 (517, np.float64(0.0)),
 (518, np.float64(0.0)),
 (519, np.float64(0.0)),
 (520, np.float64(0.0)),
 (521, np.float64(0.031750031750047626)),
 (522, np.float64(0.0)),
 (523, np.float64(0.0)),
 (524, np.float64(0.0)),
 (525, np.float64(0.0)),
 (526, np.float64(0.0)),
 (527, np.float64(0.0)),
 (528, np.float64(0.0)),
 (529, np.float64(0.11359236684941297)),
 (530, np.float64(0.041204282171516456)),
 (531, np.float64(0.0)),
 (532, np.float64(0.024906774069335898)),
 (533, np.float64(0.041204282171516456)),
 (534, np.float64(0.0)),
 (535, np.float64(0.031750031750047626)),
 (536, np.float64(0.0582716546748065)),
 (537, np.float64(0.0)),
 (538, np.float64(0.0)),
 (539, np.float64(0.20739033894608508)),
 (540, np.float64(0.0)),
 (541, np.float64(0.025149772741392844)),
 (542, np.float64(0.0)),
 (543, np.float64(0.0)),
 (544, np.float64(0.0)),
 (545, np.float64(0.0)),
 (546, np.float64(0.04233337566673017)),
 (547, np.float64(0.0)),
 (548, np.float64(0.0)),
 (549, np.float64(0.1070959105203332)),
 (550, np.float64(0.03126526997403613)),
 (551, np.float64(0.0)),
 (552, np.float64(0.0)),
 (553, np.float64(0.0)),
 (554, np.float64(0.0)),
 (555, np.float64(0.0181428752857415)),
 (556, np.float64(0.0)),
 (557, np.float64(0.13116516715679058)),
 (558, np.float64(0.0)),
 (559, np.float64(0.0)),
 (560, np.float64(0.024670685574572422)),
 (561, np.float64(0.0)),
 (562, np.float64(0.0)),
 (563, np.float64(0.0)),
 (564, np.float64(0.07838618016696206)),
 (565, np.float64(0.0)),
 (566, np.float64(0.0)),
 (567, np.float64(0.0)),
 (568, np.float64(0.09677419354838711)),
 (569, np.float64(0.0)),
 (570, np.float64(0.04233337566673017)),
 (571, np.float64(0.0)),
 (572, np.float64(0.0)),
 (573, np.float64(0.0)),
 (574, np.float64(0.0)),
 (575, np.float64(0.0)),
 (576, np.float64(0.0)),
 (577, np.float64(0.06913011298202835)),
 (578, np.float64(0.028049635672660722)),
 (579, np.float64(0.10776318121606496)),
 (580, np.float64(0.0)),
 (581, np.float64(0.07658395810674835)),
 (582, np.float64(0.21185085653295044)),
 (583, np.float64(0.0)),
 (584, np.float64(0.0)),
 (585, np.float64(0.0)),
 (586, np.float64(0.0)),
 (587, np.float64(0.0)),
 (588, np.float64(0.031750031750047626)),
 (589, np.float64(0.05542739954736933)),
 (590, np.float64(0.0)),
 (591, np.float64(0.0)),
 (592, np.float64(0.0)),
 (593, np.float64(0.0)),
 (594, np.float64(0.0)),
 (595, np.float64(0.08980265101338746)),
 (596, np.float64(0.02707651805369412)),
 (597, np.float64(0.0)),
 (598, np.float64(0.0)),
 (599, np.float64(0.036854230359837384)),
 (600, np.float64(0.026481357066618805)),
 (601, np.float64(0.0)),
 (602, np.float64(0.0)),
 (603, np.float64(0.0)),
 (604, np.float64(0.0)),
 (605, np.float64(0.0)),
 (606, np.float64(0.0)),
 (607, np.float64(0.0)),
 (608, np.float64(0.0)),
 (609, np.float64(0.0)),
 (610, np.float64(0.0)),
 (611, np.float64(0.0)),
 (612, np.float64(0.0)),
 (613, np.float64(0.0)),
 (614, np.float64(0.06670373459650701)),
 (615, np.float64(0.0)),
 (616, np.float64(0.0)),
 (617, np.float64(0.032791291789197645)),
 (618, np.float64(0.0)),
 (619, np.float64(0.0)),
 (620, np.float64(0.0)),
 (621, np.float64(0.041204282171516456)),
 (622, np.float64(0.0)),
 (623, np.float64(0.0)),
 (624, np.float64(0.048001536073731935)),
 (625, np.float64(0.0)),
 (626, np.float64(0.06451612903225808)),
 (627, np.float64(0.0)),
 (628, np.float64(0.0)),
 (629, np.float64(0.027713699773684666)),
 (630, np.float64(0.0)),
 (631, np.float64(0.0)),
 (632, np.float64(0.06160411036336974)),
 (633, np.float64(0.0)),
 (634, np.float64(0.031750031750047626)),
 (635, np.float64(0.08122955416108235)),
 (636, np.float64(0.0)),
 (637, np.float64(0.02913582733740325)),
 (638, np.float64(0.0)),
 (639, np.float64(0.0)),
 (640, np.float64(0.0)),
 (641, np.float64(0.0)),

In [60]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]#sorting is done on second number basis

[(3606, np.float64(0.21997067253202995)),
 (1214, np.float64(0.21304071579547101)),
 (582, np.float64(0.21185085653295044)),
 (1916, np.float64(0.20953951903123738)),
 (539, np.float64(0.20739033894608508))]

Recommend

In [61]:
def recommend(movie):
    movie_index=new_movie[new_movie['title']==movie].index[0] 
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i  in movies_list:
        print(new_movie.iloc[i[0]].title)

In [62]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman v Superman: Dawn of Justice
Batman

In [63]:
new_movie.iloc[1216].title

'Autumn in New York'

In [64]:
new_movie.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   4806 non-null   object
 1   id      4806 non-null   int64
 2   tags    4806 non-null   object
dtypes: int64(1), object(2)
memory usage: 279.2+ KB

In [65]:
new_movie[new_movie['title']=='Batman Begins'].index[0]

np.int64(119)

Deployment

In [66]:
import pickle as pkl

In [67]:
pkl.dump(new_movie,open('movies.pkl','wb'))

In [68]:
pkl.dump(new_movie.to_dict(),open('movie_dic.pkl','wb'))

In [69]:
pkl.dump(similarity,open('similarity.pkl','wb'))